# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Event Checker

on: 
  push:
    branches:
      - master
  schedule:
    - cron: "30 0,6,9,12,15,18,21 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - uses: actions/checkout@v2
    - uses: c-hive/gha-npm-cache@v1
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: Install NPM Package
      run: npm install
    - name: Create .env file
      run: |
        touch .env
        echo BOTTOKEN=${{ secrets.BOTTOKEN }} >> .env
        echo CHANNELID=${{ secrets.CHANNELID }} >> .env
        echo CLIENTAUTH=${{ secrets.CLIENTAUTH }} >> .env
    - name: Run Script
      run: npm run start
    - name: Update Last Check
      run: TZ='Asia/Jakarta' date +%c > lastCheck
    - name: Push LogFile
      run: |
        git config --global user.name 'Tukang Info'
        git config --global user.email 'TukangInfo@users.noreply.github.com'
        git add .
        git commit -am "Checker"
        git push
    
